import {
  AudioFilled,
  GroupOutlined,
  PropertySafetyFilled,
} from "@ant-design/icons";
import { uniqueId } from "lodash";
import {
  Aperture,
  Article,
  BrandProducthunt,
  Category,
  Home,
  LayoutAlignBottom,
  LayoutSidebar,
  MailOpened,
  MasksTheater,
  Message2,
  Note,
  Notebook,
  Planet,
  Point,
  QuestionMark,
  Settings,
  Speakerphone,
  Square,
  Stack3,
  User,
  UserCheck,
  Video,
  Vip,
} from "tabler-icons-react";
import { MenuitemProps } from "../types/menuItem";
import { Group } from "antd/es/avatar";

export const Menuitems: MenuitemProps[] = [
  {
    id: uniqueId(),
    title: "داشبورد",
    icon: Aperture,
    href: "/",
    accessKey: ["admin_profile", "subscriber"],
    chip: "New",
    chipColor: "secondary",
  },
  {
    id: uniqueId(),
    subheader: "مدیریت کاربران",
    navlabel: true,
    accessKey: ["smart-doc"],
  },
  {
    id: uniqueId(),
    title: "کاربران",
    icon: User,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/user-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/user-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "اعضا",
    icon: UserCheck,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/team-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/team-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    subheader: "مدیریت محصولات",
    navlabel: true,
    accessKey: ["smart-doc"],
  },
  {
    id: uniqueId(),
    title: "دسته بندی ها",
    icon: Category,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/category-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/category-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "محصولات",
    icon: BrandProducthunt,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/product-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/product-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "گروه ها",
    icon: GroupOutlined,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/group-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/group-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "ویژگی های محصول",
    icon: PropertySafetyFilled,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/property-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/property-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   subheader: "تنظمیات صفحه اصلی",
  //   navlabel: true,
  //   accessKey: ["smart-doc"],
  // },
  // {
  //   id: uniqueId(),
  //   title: "محصولات صفحه اصلی",
  //   icon: Home,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "افزودن",
  //       icon: Point,
  //       href: "/home/products-create",
  //       accessKey: ["doc-create"],
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "لیست",
  //       icon: Point,
  //       href: "/home/products-list",
  //       accessKey: ["normal-doc-list"],
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "ویدیو های صفحه اصلی",
  //   icon: Video,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "افزودن",
  //       icon: Point,
  //       href: "/home/videos-create",
  //       accessKey: ["doc-create"],
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "لیست",
  //       icon: Point,
  //       href: "/home/videos-list",
  //       accessKey: ["normal-doc-list"],
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "نظرات صفحه اصلی",
  //   icon: Note,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "افزودن",
  //       icon: Point,
  //       href: "/home/comments-create",
  //       accessKey: ["doc-create"],
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "لیست",
  //       icon: Point,
  //       href: "/home/comments-list",
  //       accessKey: ["normal-doc-list"],
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "خدمات صفحه اصلی",
  //   icon: Square,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "افزودن",
  //       icon: Point,
  //       href: "/home/services-create",
  //       accessKey: ["doc-create"],
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "لیست",
  //       icon: Point,
  //       href: "/home/services-list",
  //       accessKey: ["normal-doc-list"],
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "تنظیمات فوتر",
  //   icon: LayoutAlignBottom,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "افزودن",
  //       icon: Point,
  //       href: "/footer-create",
  //       accessKey: ["doc-create"],
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "لیست",
  //       icon: Point,
  //       href: "/footer-list",
  //       accessKey: ["normal-doc-list"],
  //     },
  //   ],
  // },
  {
    id: uniqueId(),
    subheader: "تنظمیات سایت",
    navlabel: true,
    accessKey: ["smart-doc"],
  },
  {
    id: uniqueId(),
    title: "مقالات",
    icon: Article,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/blog-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/blog-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "سوالات متداول",
    icon: QuestionMark,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/faq-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/faq-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "هدر",
    icon: Stack3,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/header-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/header-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "نظرات",
    icon: Message2,
    href: "/comment-list",
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/comment-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/comment-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "تیکت ها",
    icon: Speakerphone,
    href: "/ticket-list",
  },

  {
    id: uniqueId(),
    title: "تنظیمات",
    icon: Settings,
    href: "/settings",
  },
];
