import {
  GroupOutlined,
  LinkOutlined,
  PropertySafetyFilled,
} from "@ant-design/icons";
import { uniqueId } from "lodash";
import {
  Aperture,
  Article,
  BrandProducthunt,
  Category,
  History,
  Home,
  Message2,
  Point,
  QuestionMark,
  Settings,
  Square,
  Stack3,
  User,
  UserCheck,
  Video,
} from "tabler-icons-react";
import { MenuitemProps } from "../types/menuItem";

export const Menuitems: MenuitemProps[] = [
  {
    id: uniqueId(),
    title: "داشبورد",
    icon: Aperture,
    href: "/",
    accessKey: ["admin_profile", "subscriber"],
    chip: "New",
    chipColor: "secondary",
  },
  {
    id: uniqueId(),
    subheader: "مدیریت کاربران",
    navlabel: true,
    accessKey: ["smart-doc"],
  },
  {
    id: uniqueId(),
    title: "کاربران",
    icon: User,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/user-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/user-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "اعضا",
    icon: UserCheck,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/team-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/team-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    subheader: "مدیریت محصولات",
    navlabel: true,
    accessKey: ["smart-doc"],
  },
  {
    id: uniqueId(),
    title: "دسته بندی ها",
    icon: Category,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/category-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/category-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "محصولات",
    icon: BrandProducthunt,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/product-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/product-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "گروه ها",
    icon: GroupOutlined,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/group-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/group-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "ویژگی های محصول",
    icon: PropertySafetyFilled,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/property-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/property-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "تاریخچه قیمت",
    icon: History,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/history-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/history-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    subheader: "تنظمیات صفحه اصلی",
    navlabel: true,
    accessKey: ["smart-doc"],
  },
  {
    id: uniqueId(),
    title: "قیمت لحظه ایی و رقابتی",
    icon: Home,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/home_momentPrices-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/home_momentPrices-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   title: "قیمت روز آهن آلات",
  //   icon: Video,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "افزودن",
  //       icon: Point,
  //       href: "/home_dayPrices-create",
  //       accessKey: ["doc-create"],
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "لیست",
  //       icon: Point,
  //       href: "/home_dayPrices-list",
  //       accessKey: ["normal-doc-list"],
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "قیمت روز محصولات",
  //   icon: Square,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "افزودن",
  //       icon: Point,
  //       href: "/home_recentPrices-create",
  //       accessKey: ["doc-create"],
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "لیست",
  //       icon: Point,
  //       href: "/home_recentPrices-list",
  //       accessKey: ["normal-doc-list"],
  //     },
  //   ],
  // },
  {
    id: uniqueId(),
    title: "دسته بندی های صفحه اصلی",
    icon: Square,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/home-category-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/home-category-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    subheader: "تنظمیات سایت",
    navlabel: true,
    accessKey: ["smart-doc"],
  },
  {
    id: uniqueId(),
    title: "مقالات",
    icon: Article,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/blog-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/blog-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "سوالات متداول",
    icon: QuestionMark,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/faq-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/faq-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "هدر",
    icon: Stack3,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/header-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/header-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "نظرات",
    icon: Message2,
    href: "/comments-list",
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/comments-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/comments-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "لینک های مفید",
    icon: LinkOutlined,
    href: "/usefullinks-list",
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/usefullinks-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/usefullinks-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   title: "تیکت ها",
  //   icon: Speakerphone,
  //   href: "/ticket-list",
  // },

  {
    id: uniqueId(),
    title: "تنظیمات",
    icon: Settings,
    href: "/settings",
  },
];
