import {
  GroupOutlined,
  LinkOutlined,
  PropertySafetyFilled,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { uniqueId } from "lodash";
import {
  AccessPoint,
  Aperture,
  Article,
  BrandProducthunt,
  Category,
  Headphones,
  History,
  Home,
  Message2,
  Point,
  QuestionMark,
  Settings,
  Square,
  Stack3,
  User,
  UserCheck,
  UserCircle,
  Video,
} from "tabler-icons-react";
import { MenuitemProps } from "../types/menuItem";

export const Menuitems: MenuitemProps[] = [
  {
    id: uniqueId(),
    title: "داشبورد",
    icon: Aperture,
    href: "/",
    accessKey: ["admin_profile", "subscriber"],
    chip: "New",
    chipColor: "secondary",
  },
  {
    id: uniqueId(),
    subheader: "مدیریت کاربران",
    navlabel: true,
    accessKey: [
      "admin_users_read",
      "admin_user_create",
      "admin_team_infos_read",
      "admin_team_info_create",
    ],
  },
  {
    id: uniqueId(),
    title: "مدیران",
    icon: UserCircle,
    accessKey: ["admin_users_read", "admin_user_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/admin-create",
        accessKey: ["admin_user_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/admin-list",
        accessKey: ["admin_users_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "کاربران",
    icon: User,
    accessKey: ["admin_users_read", "admin_user_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/user-create",
        accessKey: ["admin_user_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/user-list",
        accessKey: ["admin_users_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "اعضا",
    icon: UserCheck,
    accessKey: ["admin_team_infos_read", "admin_team_info_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/team-create",
        accessKey: ["admin_team_info_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/team-list",
        accessKey: ["admin_team_infos_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "نقش ها",
    icon: AccessPoint,
    accessKey: ["admin_roles_read", "admin_role_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/role-create",
        accessKey: ["admin_role_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/role-list",
        accessKey: ["admin_roles_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    subheader: "مدیریت محصولات",
    navlabel: true,
    accessKey: [
      "admin_categories_read",
      "admin_category_create",
      "admin_products_read",
      "admin_product_create",
      "admin_groups_read",
      "admin_group_create",
      "admin_groups_read",
      "admin_group_create",
      "admin_properties_read",
      "admin_property_create",
    ],
  },
  {
    id: uniqueId(),
    title: "دسته بندی ها",
    icon: Category,
    accessKey: ["admin_categories_read", "admin_category_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/category-create",
        accessKey: ["admin_category_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/category-list",
        accessKey: ["admin_categories_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "محصولات",
    accessKey: ["admin_products_read", "admin_product_create"],
    icon: BrandProducthunt,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/product-create",
        accessKey: ["admin_product_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/product-list",
        accessKey: ["admin_products_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "گروه ها",
    icon: GroupOutlined,
    accessKey: ["admin_groups_read", "admin_group_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/group-create",
        accessKey: ["admin_group_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/group-list",
        accessKey: ["admin_groups_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "ویژگی های محصول",
    icon: PropertySafetyFilled,
    accessKey: ["admin_properties_read", "admin_property_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/property-create",
        accessKey: ["admin_property_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/property-list",
        accessKey: ["admin_properties_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "تاریخچه قیمت",
    accessKey: [
      "admin_product_price_histories_read",
      "admin_product_price_history_create",
    ],
    icon: History,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/history-create",
        accessKey: ["admin_product_price_history_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/history-list",
        accessKey: ["admin_product_price_histories_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    subheader: "تنظمیات صفحه اصلی",
    navlabel: true,
    accessKey: [
      "admin_moment_prices_read",
      "admin_moment_price_create",
      "admin_category_views_read",
      "admin_category_view_create",
    ],
  },
  {
    id: uniqueId(),
    title: "قیمت لحظه ایی و رقابتی",
    icon: Home,
    accessKey: ["admin_moment_prices_read", "admin_moment_price_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/home_momentPrices-create",
        accessKey: ["admin_moment_price_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/home_momentPrices-list",
        accessKey: ["admin_moment_prices_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "دسته بندی های صفحه اصلی",
    icon: Square,
    accessKey: ["admin_category_views_read", "admin_category_view_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/home-category-create",
        accessKey: ["admin_category_views_read"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/home-category-list",
        accessKey: ["admin_category_view_create"],
      },
    ],
  },
  {
    id: uniqueId(),
    subheader: "تنظمیات سایت",
    navlabel: true,
    accessKey: [
      "admin_blogs_read",
      "admin_blog_create",
      "admin_videos_read",
      "admin_video_create",
      "admin_faqs_read",
      "admin_faq_create",
      "admin_headers_read",
      "admin_header_create",
    ],
  },
  {
    id: uniqueId(),
    title: "مقالات",
    accessKey: ["admin_blogs_read", "admin_blog_create"],
    icon: Article,
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/blog-create",
        accessKey: ["admin_blog_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/blog-list",
        accessKey: ["admin_blogs_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "ویدیو ها",
    icon: VideoCameraOutlined,
    accessKey: ["admin_videos_read", "admin_video_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/videos-create",
        accessKey: ["admin_video_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/videos-list",
        accessKey: ["admin_videos_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "سوالات متداول",
    icon: QuestionMark,
    accessKey: ["admin_faqs_read", "admin_faq_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/faq-create",
        accessKey: ["admin_faq_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/faq-list",
        accessKey: ["admin_faqs_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "هدر",
    icon: Stack3,
    accessKey: ["admin_headers_read", "admin_header_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/header-create",
        accessKey: ["doc-create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/header-list",
        accessKey: ["normal-doc-list"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "درخواست های قیمت",
    icon: Headphones,
    href: "/request-prices-list",
    accessKey: ["admin_price_requests_read"],
  },
  {
    accessKey: ["admin_comments_read", "admin_comment_create"],
    id: uniqueId(),
    title: "نظرات",
    icon: Message2,
    href: "/comments-list",
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/comments-create",
        accessKey: ["admin_comment_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/comments-list",
        accessKey: ["admin_comments_read"],
      },
    ],
  },
  {
    id: uniqueId(),
    title: "لینک های مفید",
    icon: LinkOutlined,
    href: "/usefullinks-list",
    accessKey: ["admin_useful_links_read", "admin_useful_link_create"],
    children: [
      {
        id: uniqueId(),
        title: "افزودن",
        icon: Point,
        href: "/usefullinks-create",
        accessKey: ["admin_useful_link_create"],
      },
      {
        id: uniqueId(),
        title: "لیست",
        icon: Point,
        href: "/usefullinks-list",
        accessKey: ["admin_useful_links_read"],
      },
    ],
  },

  {
    id: uniqueId(),
    title: "تنظیمات",
    icon: Settings,
    href: "/settings",
    accessKey: ["admin_settings_read"],
  },
];
