export const adminPermissions = [
  "admin_categories_read",
  "admin_category_read",
  "admin_category_create",
  "admin_category_update",
  "admin_category_delete",

  "admin_products_read",
  "admin_product_read",
  "admin_product_create",
  "admin_product_update",
  "admin_product_delete",

  "admin_product_cores_read",
  "admin_product_core_read",
  "admin_product_core_create",
  "admin_product_core_update",
  "admin_product_core_delete",

  "admin_product_price_history_export",
  "admin_product_price_histories_read",
  "admin_product_price_history_read",
  "admin_product_price_history_create",
  "admin_product_price_history_update",
  "admin_product_price_history_delete",

  "admin_properties_read",
  "admin_property_read",
  "admin_property_create",
  "admin_property_update",
  "admin_property_delete",

  "admin_groups_read",
  "admin_group_read",
  "admin_group_create",
  "admin_group_update",
  "admin_group_delete",

  "admin_faqs_read",
  "admin_faq_read",
  "admin_faq_create",
  "admin_faq_update",
  "admin_faq_delete",

  "admin_team_infos_read",
  "admin_team_info_read",
  "admin_team_info_create",
  "admin_team_info_update",
  "admin_team_info_delete",

  "admin_useful_links_read",
  "admin_useful_link_read",
  "admin_useful_link_create",
  "admin_useful_link_update",
  "admin_useful_link_delete",

  "admin_users_read",
  "admin_user_read",
  "admin_user_create",
  "admin_user_update",
  "admin_user_delete",

  "admin_comments_read",
  "admin_comment_read",
  "admin_comment_create",
  "admin_comment_update",
  "admin_comment_delete",

  "admin_settings_read",
  "admin_settings_create_or_update",

  "admin_category_views_read",
  "admin_category_view_read",
  "admin_category_view_create",
  "admin_category_view_update",
  "admin_category_view_delete",

  "admin_blogs_read",
  "admin_blog_read",
  "admin_blog_image_upload",
  "admin_blog_create",
  "admin_blog_update",
  "admin_blog_delete",

  "admin_moment_prices_read",
  "admin_moment_price_read",
  "admin_moment_price_create",
  "admin_moment_price_update",
  "admin_moment_price_delete",

  "admin_videos_read",
  "admin_video_read",
  "admin_video_create",
  "admin_video_update",
  "admin_video_delete",

  "admin_price_requests_read",
  "admin_price_request_read",
  "admin_price_request_status_update",
  "admin_price_request_delete",

  "admin_headers_read",
  "admin_header_read",
  "admin_header_create",
  "admin_header_update",
  "admin_header_delete",

  "admin_admins_read",
  "admin_admin_read",
  "admin_admin_create",
  "admin_admin_update",
  "admin_admin_delete",
];
